#!/bin/sh

#--ATF prompt for mysql binaries path and user/pwd to connect
echo -n "Path to MySQL binaries [default /usr/bin]: "
read MYPATH
if [ "${MYPATH}" = "" ]; then
  MYPATH=/usr/bin
fi
echo -n "MySQL user account [default root]: "
read MYUSR
if [ "${MYUSR}" = "" ]; then
  MYUSR=root
fi
echo -n "MySQL password for ${MYUSR}@localhost [default (none)]: "
STTY_ECHO=`stty -g`
stty -echo
read MYPWD
stty ${STTY_ECHO}
CMD="${MYPATH}/mysql --user=${MYUSR} --password=${MYPWD}"
#--atf


cd /pos/installation/mysql/script

${CMD} < create_lane_db


cd ../opdata/tables

${CMD} < chargecode.table
${CMD} < couponcodes.table
${CMD} < custdata.table
${CMD} < departments.table
${CMD} < employees.table
${CMD} < globalvalues.table
${CMD} < products.table
${CMD} < promomsgs.table
${CMD} < tenders.table
${CMD} < taxtable.table

cd ../data

${CMD} < couponcodes.insert
${CMD} < custdata.insert
${CMD} < departments.insert
${CMD} < employees.insert
${CMD} < globalvalues.insert
echo "1\n"
${CMD} < products.insert
echo "2\n"
${CMD} < tenders.insert
echo "3\n"
${CMD} < taxtable.insert

cd ../views
echo "4\n"
${CMD} < chargecodeview.viw
echo "5\n"
${CMD} < memchargebalance.viw


cd ../../translog/tables

${CMD} < activities.table
${CMD} < activitylog.table
${CMD} < activitytemplog.table
${CMD} < alog.table
${CMD} < dtransactions.table
${CMD} < localtemptrans.table
${CMD} < localtrans.table
${CMD} < localtransarchive.table
${CMD} < suspended.table


cd ../views

${CMD} < localtranstoday.viw
${CMD} < suspendedtoday.viw
${CMD} < suspendedlist.viw


${CMD} < lttsummary.viw
${CMD} < lttsubtotals.viw
${CMD} < subtotals.viw

${CMD} < ltt_receipt.viw
${CMD} < receipt.viw

${CMD} < rp_ltt_receipt.viw
${CMD} < rp_receipt_header.viw
${CMD} < rp_receipt.viw
${CMD} < rp_list.viw

${CMD} < screendisplay.viw

${CMD} < memdiscountadd.viw
${CMD} < memdiscountremove.viw
${CMD} < staffdiscountadd.viw
${CMD} < staffdiscountremove.viw

${CMD} < memchargetotals.viw




cd ../../is4c_op/tables

${CMD} < couponcodes.table
${CMD} < custdata.table
${CMD} < chargecode.table
${CMD} < departments.table
${CMD} < employees.table
${CMD} < products.table
${CMD} < tenders.table

cd /pos/installation/mysql/is4c_log/tables/

${CMD} < activitylog.table
${CMD} < dtransactions.table
${CMD} < suspended.table


cd /pos/installation/mysql/is4c_log/views/


${CMD} < dlog.viw
${CMD} < tendertape.viw
${CMD} < buspasstotals.viw
${CMD} < cctenders.viw
${CMD} < cctendertotal.viw
${CMD} < cktenders.viw
${CMD} < cktendertotal.viw
${CMD} < dctenders.viw
${CMD} < dctendertotal.viw
${CMD} < fstenders.viw
${CMD} < fstendertotal.viw
${CMD} < memchargebalance.viw
${CMD} < memchargetotals.viw
${CMD} < mitenders.viw
${CMD} < mitendertotal.viw
${CMD} < suspendedtoday.viw



cd ../../script

${CMD} < create_lane_acct

cd ..
cd ..

echo "Done"
